DguFarmSystem/4th-security-Jarvis-FE

.gitignore
package.json
pnpm-lock.yaml
src/stories/Button.tsx
src/stories/Header.tsx

Vercel CLI를 이용해 프로젝트 정식 배포(Production)를 완료했습니다.
포크한 리포지토리 기준으로 우회 배포를 설정하고, Vercel 프로젝트 연결 및 빌드 에러 수정 작업도 함께 진행했습니다.

[fix] bug/#3 Deploy Error Completed

---

src/components/atoms/Button/Button.stories.tsx
src/components/atoms/Button/index.tsx

Button 컴포넌트를 구현했습니다.
Default로 재사용 가능한 컴포넌트와 기능에서 필요한 세부 버튼을 디자인에 맞게 구현했습니다.
기능별 세부 버튼을 디자인에 맞게 구현
- login
- auth
- auth-cancel
- connect
- addUser
- createRole
- save
- toggle
toggle의 경우 활성화와 비활성화 상태로 구분하여 클릭 시 상태가 바뀌도록 구성

Feat#9 Implemented Button

---

src/components/atoms/Management/UserManagement/index.tsx

[fix] deleted email from component

---

vercel.json

chore: add vercel.json for SPA routing support

---

src/App.tsx

[feat] rendered dashboard page

---

src/components/atoms/ResourceTrendsChart/index.tsx

[fix] changed graph layout

---

src/components/atoms/ResourceTrendsChart/index.tsx

[fix] change chart style

---

src/components/atoms/Log/index.tsx
src/pages/SessionPage/index.tsx

[test] print output to queue

---

src/pages/SessionPage/index.tsx

[fix] resolved json parsing error

---

src/index.css

[feat] global background

---

src/components/atoms/Modal/LoginModal/index.tsx
src/components/atoms/Modal/UpdateUserModal/index.tsx

[fix] changed UpdateUserModal style

---

src/components/atoms/Modal/LoginModal/index.tsx

[fix] changed Github image path error

---

src/App.tsx
src/components/atoms/Modal/LoginModal/index.tsx
src/pages/ManagementPage/index.tsx

[fix] double array error resolved

---

src/components/atoms/Modal/LoginModal/LoginModal.stories.tsx

[fix] deleted isOpen fron LoginModal.stories.tsx

---

src/App.tsx
src/pages/SessionPage/index.tsx

[fix] changed excluding cert.create in audit logs

---

src/components/Terminal/index.tsx
src/components/atoms/Tab/index.tsx
src/pages/ResourcePage/index.tsx

[fix] fixed title layout on tab

---

src/components/atoms/Modal/LoginModal/index.tsx
tsconfig.json
tsconfig.node.json
vite.config.ts

[fix] import path alias

---

src/components/atoms/Modal/SessionViewModal/index.tsx
src/pages/SessionPage/index.tsx

[fix] changed sessionmodal style

---

src/components/atoms/FilterPanel/FilterPanel.stories.tsx
src/components/atoms/FilterPanel/index.tsx
src/pages/SessionPage/index.tsx

[feat] added filtering events by types

---

src/pages/ManagementPage/index.tsx

[fix] resolved updatae role error
